# Generated by Django 3.2.5 on 2021-07-14 05:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название канала')),
                ('photo', models.CharField(max_length=200, verbose_name='Ссылка на фотографию канала')),
                ('active', models.BooleanField(default=True, verbose_name='Статус канала')),
                ('order_num', models.IntegerField(verbose_name='Приоритет канала')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст заказа')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('client_phone', models.CharField(max_length=10)),
                ('client_email', models.EmailField(max_length=254)),
                ('total_price', models.FloatField(verbose_name='Total price of order')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('NEW', 'new'), ('PAID', 'paid'), ('CLOSED', 'closed')], max_length=100, verbose_name='Order status')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('price', models.FloatField(verbose_name='Цена одного символа на определенном канале')),
                ('channels', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ads.channel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Цена выбранного канала с учетом количества дней в определенном заказе')),
                ('channels', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ads.channel')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ads.order')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(verbose_name='Discount percentage')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(default=datetime.datetime(2999, 12, 31, 0, 0))),
                ('min_days', models.IntegerField(verbose_name='Количество минимальных дней')),
                ('channels', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ads.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('order_details', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Ads.orderdetail')),
            ],
        ),
    ]
