# Generated by Django 3.2.5 on 2021-07-15 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='price',
            new_name='price_per_symbol',
        ),
    ]
